blank_issues_enabled: false
issue_templates:
  - name: "âœ¨ Feature"
    description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€"
    labels: ["feature"]
    body: feature_template.yml
  - name: "ğŸ“‹ To-Do List"
    description: "í•´ì•¼ í•  ì¼ ì •ë¦¬"
    labels: ["todo"]
    body: todo_template.yml
